version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build: .
    container_name: app
    environment:
      GO111MODULE: "on"
    tty: true
    volumes:
      - .:/go/src/try_gin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: |
      tail -f /dev/null
