version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      DATABASE_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      PGPASSWORD: postgres
  app:
    build: .
    container_name: app
    environment:
      GO111MODULE: "on"
      TZ: "Asia/Tokyo"
    tty: true
    volumes:
      - .:/go/src/try_gin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
